spring:
  jwt:
    secret: bbombbom
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  jpa:
    show-sql : true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  springdoc:
    api-docs:
      groups:
        enabled: true
    swagger-ui:
      path: /swagger-ui.html
      displayRequestDuration: true
      groups-order: DESC
  datasource:
    url: jdbc:mariadb://192.168.100.216:3306/bbom?characterEncoding=UTF-8&ServerTimezone=UTC
    username: root
    password: Laonpp00..L
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

logging:
  level:
    root: info


app:
  filePath: /Users/geumjiun/Documents/upload
fireBase:
  path: /var/app/brc/brandcare-5129a-firebase-adminsdk-q8j9j-1675ea66b8.json
mail:
  id: guemjiwoon@gmail.com
  password: wldnsdl99*
